# Generated by Django 2.0.5 on 2018-06-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180602_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=255, verbose_name='姓名')),
                ('phone', models.CharField(max_length=255, verbose_name='電話')),
            ],
        ),
    ]
