# Generated by Django 2.0.5 on 2018-06-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(default=0)),
                ('reader_id', models.IntegerField(default=0)),
                ('date_checkout', models.DateField()),
                ('date_return', models.DateField(null=True)),
            ],
        ),
    ]
