# Generated by Django 2.0.5 on 2018-06-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_circulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulation',
            name='date_checkout',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='circulation',
            name='date_return',
            field=models.DateTimeField(null=True),
        ),
    ]
